gcloud:
  region: ${gcloud_region}
  project: ${gcloud_project}
  prowterraform_gke_svc_account_key: ${prow_terraform_gcloud_svc_account_key}
gke:
  name: ${gke_name}
  authenticator_groups_security_group: ${gke_authenticator_groups_security_group}
aws:
  terraform_user_access_key_id: ${prow_terraform_aws_svc_account_access_key_id}
  terraform_user_secret_access_key: ${prow_terraform_aws_svc_account_secret_access_key}
docker:
  config: ${dockerconfig}
prow:
  baseurl: ${prow_base_url}
  bucket_svc_account_key: ${prow_bucket_svc_account_key}
  webhook_hmac_token: ${prow_webhook_hmac_token}
  cookie_secret: ${prow_cookie_secret}
  bucket_name: ${prow_artefacts_bucket_name}
  redirect_url: ${prow_redirect_url}
  final_redirect_url: ${prow_final_redirect_url}
  oauth_config: ${prow_github_oauth_config}
  job_url_template: 'https://${prow_base_url}/view/gcs/${prow_artefacts_bucket_name}/pr-logs/pull/{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  report_template: '[Full PR test history](https://${prow_base_url}/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}})'
github:
  org: ${prow_github_org}
  bot:
    token: ${prow_github_bot_token}
    ssh_key: ${prow_github_bot_ssh_key}
oauth:
  client_id: ${oauth_client_id}
  client_secret: ${oauth_client_secret}
  cookie_secret: ${oauth_cookie_secret}
certmanager:
  gke_svc_account_key: ${certmanager_svc_account_key}
slack:
  token: ${slack_token}
  report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <{{.Status.URL}}|View logs>'